openapi: 3.0.0
info:
  title: Sample API
  version: 0.0.0
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /parks/:
    get:
      summary: Returns a list of all parks
      operationId: yaws.controllers.list_parks
      responses:
        '200':
          description: A JSON array of park names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /parks/{name}/:
    get:
      summary: Returns a park info
      operationId: yaws.controllers.get_park_info
      responses:
        '200':
          description: A object containing park info
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  timezone:
                    type: string
                  type:
                    type: string

  /parks/{name}/production:
    get:
      summary: Returns a data points of the park
      operationId: yaws.controllers.get_park_production
      parameters:
        - name: name
          in: path
          description: The park to get production info from
          required: true
          schema:
            type: string
        - name: since
          in: query
          description: the earliest date to obtain data
          schema:
            type: string
            format: 'date-time'
          required: true
        - name: till
          in: query
          description: the latest date to obtain data
          required: false
          schema:
            type: string
            format: 'date-time'
            default: '2032-12-31T23:59:59.0Z'
      responses:
        '200':
          description: A list of data points
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    at:
                      type: string
                      format: 'date-time'
                    power:
                      type: number
                      description: In MW